//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BivConnection.CSStatusInformatieService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class foutType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string foutcodeField;
        
        private string foutbeschrijvingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string foutcode {
            get {
                return this.foutcodeField;
            }
            set {
                this.foutcodeField = value;
                this.RaisePropertyChanged("foutcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string foutbeschrijving {
            get {
                return this.foutbeschrijvingField;
            }
            set {
                this.foutbeschrijvingField = value;
                this.RaisePropertyChanged("foutbeschrijving");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class identiteitType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nummerField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string nummer {
            get {
                return this.nummerField;
            }
            set {
                this.nummerField = value;
                this.RaisePropertyChanged("nummer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/", ConfigurationName="CSStatusInformatieService.StatusinformatieService_V1_2", ProtectionLevel = System.Net.Security.ProtectionLevel.Sign)]
    public interface StatusinformatieService_V1_2 {
        
        // CODEGEN: Generating message contract since the operation getBerichtsoorten is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getBerichtsoortenRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getBerichtsoortenResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BivConnection.CSStatusInformatieService.foutType), Action="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getBerichtsoorten/Fault/", Name="statusinformatieFault", Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BivConnection.CSStatusInformatieService.getBerichtsoortenResponse1 getBerichtsoorten(BivConnection.CSStatusInformatieService.getBerichtsoortenRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getBerichtsoortenRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getBerichtsoortenResponse")]
        System.Threading.Tasks.Task<BivConnection.CSStatusInformatieService.getBerichtsoortenResponse1> getBerichtsoortenAsync(BivConnection.CSStatusInformatieService.getBerichtsoortenRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getProcessen is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getProcessenRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getProcessenResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BivConnection.CSStatusInformatieService.foutType), Action="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getProcessen/Fault/", Name="statusinformatieFault", Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BivConnection.CSStatusInformatieService.getProcessenResponse1 getProcessen(BivConnection.CSStatusInformatieService.getProcessenRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getProcessenRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getProcessenResponse")]
        System.Threading.Tasks.Task<BivConnection.CSStatusInformatieService.getProcessenResponse1> getProcessenAsync(BivConnection.CSStatusInformatieService.getProcessenRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getStatussenProces is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getStatussenProcesRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getStatussenProcesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BivConnection.CSStatusInformatieService.foutType), Action="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getStatussenProces/Fault/", Name="statusinformatieFault", Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BivConnection.CSStatusInformatieService.getStatussenProcesResponse1 getStatussenProces(BivConnection.CSStatusInformatieService.getStatussenProcesRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getStatussenProcesRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getStatussenProcesResponse")]
        System.Threading.Tasks.Task<BivConnection.CSStatusInformatieService.getStatussenProcesResponse1> getStatussenProcesAsync(BivConnection.CSStatusInformatieService.getStatussenProcesRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getNieuweStatussenProces is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getNieuweStatussenProcesRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getNieuweStatussenProcesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BivConnection.CSStatusInformatieService.foutType), Action="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getNieuweStatussenProces/Fault/", Name="statusinformatieFault", Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BivConnection.CSStatusInformatieService.getNieuweStatussenProcesResponse1 getNieuweStatussenProces(BivConnection.CSStatusInformatieService.getNieuweStatussenProcesRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getNieuweStatussenProcesRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getNieuweStatussenProcesResponse")]
        System.Threading.Tasks.Task<BivConnection.CSStatusInformatieService.getNieuweStatussenProcesResponse1> getNieuweStatussenProcesAsync(BivConnection.CSStatusInformatieService.getNieuweStatussenProcesRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getNieuweStatussen is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getNieuweStatussenRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getNieuweStatussenResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BivConnection.CSStatusInformatieService.foutType), Action="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getNieuweStatussen/Fault/", Name="statusinformatieFault", Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BivConnection.CSStatusInformatieService.getNieuweStatussenResponse1 getNieuweStatussen(BivConnection.CSStatusInformatieService.getNieuweStatussenRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getNieuweStatussenRequest", ReplyAction="http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/StatusinformatieSe" +
            "rvice/getNieuweStatussenResponse")]
        System.Threading.Tasks.Task<BivConnection.CSStatusInformatieService.getNieuweStatussenResponse1> getNieuweStatussenAsync(BivConnection.CSStatusInformatieService.getNieuweStatussenRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getBerichtsoortenRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private identiteitType identiteitBelanghebbendeField;
        
        private string autorisatieAdresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public identiteitType identiteitBelanghebbende {
            get {
                return this.identiteitBelanghebbendeField;
            }
            set {
                this.identiteitBelanghebbendeField = value;
                this.RaisePropertyChanged("identiteitBelanghebbende");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=1)]
        public string autorisatieAdres {
            get {
                return this.autorisatieAdresField;
            }
            set {
                this.autorisatieAdresField = value;
                this.RaisePropertyChanged("autorisatieAdres");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getBerichtsoortenResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] getBerichtsoortenReturnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("berichtsoort", DataType="normalizedString", IsNullable=false)]
        public string[] getBerichtsoortenReturn {
            get {
                return this.getBerichtsoortenReturnField;
            }
            set {
                this.getBerichtsoortenReturnField = value;
                this.RaisePropertyChanged("getBerichtsoortenReturn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBerichtsoortenRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public BivConnection.CSStatusInformatieService.getBerichtsoortenRequest getBerichtsoortenRequest;
        
        public getBerichtsoortenRequest1() {
        }
        
        public getBerichtsoortenRequest1(BivConnection.CSStatusInformatieService.getBerichtsoortenRequest getBerichtsoortenRequest) {
            this.getBerichtsoortenRequest = getBerichtsoortenRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBerichtsoortenResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public BivConnection.CSStatusInformatieService.getBerichtsoortenResponse getBerichtsoortenResponse;
        
        public getBerichtsoortenResponse1() {
        }
        
        public getBerichtsoortenResponse1(BivConnection.CSStatusInformatieService.getBerichtsoortenResponse getBerichtsoortenResponse) {
            this.getBerichtsoortenResponse = getBerichtsoortenResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getProcessenRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string berichtsoortField;
        
        private identiteitType identiteitBelanghebbendeField;
        
        private string autorisatieAdresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string berichtsoort {
            get {
                return this.berichtsoortField;
            }
            set {
                this.berichtsoortField = value;
                this.RaisePropertyChanged("berichtsoort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public identiteitType identiteitBelanghebbende {
            get {
                return this.identiteitBelanghebbendeField;
            }
            set {
                this.identiteitBelanghebbendeField = value;
                this.RaisePropertyChanged("identiteitBelanghebbende");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=2)]
        public string autorisatieAdres {
            get {
                return this.autorisatieAdresField;
            }
            set {
                this.autorisatieAdresField = value;
                this.RaisePropertyChanged("autorisatieAdres");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getProcessenResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ProcesResultaat[] getProcessenReturnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ProcesResultaat[] getProcessenReturn {
            get {
                return this.getProcessenReturnField;
            }
            set {
                this.getProcessenReturnField = value;
                this.RaisePropertyChanged("getProcessenReturn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class ProcesResultaat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kenmerkField;
        
        private string berichtsoortField;
        
        private identiteitType identiteitBelanghebbendeField;
        
        private identiteitType identiteitOntvangerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string kenmerk {
            get {
                return this.kenmerkField;
            }
            set {
                this.kenmerkField = value;
                this.RaisePropertyChanged("kenmerk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string berichtsoort {
            get {
                return this.berichtsoortField;
            }
            set {
                this.berichtsoortField = value;
                this.RaisePropertyChanged("berichtsoort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public identiteitType identiteitBelanghebbende {
            get {
                return this.identiteitBelanghebbendeField;
            }
            set {
                this.identiteitBelanghebbendeField = value;
                this.RaisePropertyChanged("identiteitBelanghebbende");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public identiteitType identiteitOntvanger {
            get {
                return this.identiteitOntvangerField;
            }
            set {
                this.identiteitOntvangerField = value;
                this.RaisePropertyChanged("identiteitOntvanger");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProcessenRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public BivConnection.CSStatusInformatieService.getProcessenRequest getProcessenRequest;
        
        public getProcessenRequest1() {
        }
        
        public getProcessenRequest1(BivConnection.CSStatusInformatieService.getProcessenRequest getProcessenRequest) {
            this.getProcessenRequest = getProcessenRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProcessenResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public BivConnection.CSStatusInformatieService.getProcessenResponse getProcessenResponse;
        
        public getProcessenResponse1() {
        }
        
        public getProcessenResponse1(BivConnection.CSStatusInformatieService.getProcessenResponse getProcessenResponse) {
            this.getProcessenResponse = getProcessenResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getStatussenProcesRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kenmerkField;
        
        private string autorisatieAdresField;
        
        private System.DateTime tijdstempelVanafField;
        
        private bool tijdstempelVanafFieldSpecified;
        
        private System.DateTime tijdstempelTotField;
        
        private bool tijdstempelTotFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string kenmerk {
            get {
                return this.kenmerkField;
            }
            set {
                this.kenmerkField = value;
                this.RaisePropertyChanged("kenmerk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=1)]
        public string autorisatieAdres {
            get {
                return this.autorisatieAdresField;
            }
            set {
                this.autorisatieAdresField = value;
                this.RaisePropertyChanged("autorisatieAdres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime tijdstempelVanaf {
            get {
                return this.tijdstempelVanafField;
            }
            set {
                this.tijdstempelVanafField = value;
                this.RaisePropertyChanged("tijdstempelVanaf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tijdstempelVanafSpecified {
            get {
                return this.tijdstempelVanafFieldSpecified;
            }
            set {
                this.tijdstempelVanafFieldSpecified = value;
                this.RaisePropertyChanged("tijdstempelVanafSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime tijdstempelTot {
            get {
                return this.tijdstempelTotField;
            }
            set {
                this.tijdstempelTotField = value;
                this.RaisePropertyChanged("tijdstempelTot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tijdstempelTotSpecified {
            get {
                return this.tijdstempelTotFieldSpecified;
            }
            set {
                this.tijdstempelTotFieldSpecified = value;
                this.RaisePropertyChanged("tijdstempelTotSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getStatussenProcesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StatusResultaat[] getStatussenProcesReturnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public StatusResultaat[] getStatussenProcesReturn {
            get {
                return this.getStatussenProcesReturnField;
            }
            set {
                this.getStatussenProcesReturnField = value;
                this.RaisePropertyChanged("getStatussenProcesReturn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class StatusResultaat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kenmerkField;
        
        private identiteitType identiteitBelanghebbendeField;
        
        private string statuscodeField;
        
        private System.DateTime tijdstempelStatusField;
        
        private string statusomschrijvingField;
        
        private foutType statusFoutcodeField;
        
        private string statusdetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string kenmerk {
            get {
                return this.kenmerkField;
            }
            set {
                this.kenmerkField = value;
                this.RaisePropertyChanged("kenmerk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public identiteitType identiteitBelanghebbende {
            get {
                return this.identiteitBelanghebbendeField;
            }
            set {
                this.identiteitBelanghebbendeField = value;
                this.RaisePropertyChanged("identiteitBelanghebbende");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=2)]
        public string statuscode {
            get {
                return this.statuscodeField;
            }
            set {
                this.statuscodeField = value;
                this.RaisePropertyChanged("statuscode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime tijdstempelStatus {
            get {
                return this.tijdstempelStatusField;
            }
            set {
                this.tijdstempelStatusField = value;
                this.RaisePropertyChanged("tijdstempelStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=4)]
        public string statusomschrijving {
            get {
                return this.statusomschrijvingField;
            }
            set {
                this.statusomschrijvingField = value;
                this.RaisePropertyChanged("statusomschrijving");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public foutType statusFoutcode {
            get {
                return this.statusFoutcodeField;
            }
            set {
                this.statusFoutcodeField = value;
                this.RaisePropertyChanged("statusFoutcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=6)]
        public string statusdetails {
            get {
                return this.statusdetailsField;
            }
            set {
                this.statusdetailsField = value;
                this.RaisePropertyChanged("statusdetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStatussenProcesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public BivConnection.CSStatusInformatieService.getStatussenProcesRequest getStatussenProcesRequest;
        
        public getStatussenProcesRequest1() {
        }
        
        public getStatussenProcesRequest1(BivConnection.CSStatusInformatieService.getStatussenProcesRequest getStatussenProcesRequest) {
            this.getStatussenProcesRequest = getStatussenProcesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStatussenProcesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public BivConnection.CSStatusInformatieService.getStatussenProcesResponse getStatussenProcesResponse;
        
        public getStatussenProcesResponse1() {
        }
        
        public getStatussenProcesResponse1(BivConnection.CSStatusInformatieService.getStatussenProcesResponse getStatussenProcesResponse) {
            this.getStatussenProcesResponse = getStatussenProcesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getNieuweStatussenProcesRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kenmerkField;
        
        private string autorisatieAdresField;
        
        private System.DateTime tijdstempelVanafField;
        
        private bool tijdstempelVanafFieldSpecified;
        
        private System.DateTime tijdstempelTotField;
        
        private bool tijdstempelTotFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string kenmerk {
            get {
                return this.kenmerkField;
            }
            set {
                this.kenmerkField = value;
                this.RaisePropertyChanged("kenmerk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=1)]
        public string autorisatieAdres {
            get {
                return this.autorisatieAdresField;
            }
            set {
                this.autorisatieAdresField = value;
                this.RaisePropertyChanged("autorisatieAdres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime tijdstempelVanaf {
            get {
                return this.tijdstempelVanafField;
            }
            set {
                this.tijdstempelVanafField = value;
                this.RaisePropertyChanged("tijdstempelVanaf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tijdstempelVanafSpecified {
            get {
                return this.tijdstempelVanafFieldSpecified;
            }
            set {
                this.tijdstempelVanafFieldSpecified = value;
                this.RaisePropertyChanged("tijdstempelVanafSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime tijdstempelTot {
            get {
                return this.tijdstempelTotField;
            }
            set {
                this.tijdstempelTotField = value;
                this.RaisePropertyChanged("tijdstempelTot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tijdstempelTotSpecified {
            get {
                return this.tijdstempelTotFieldSpecified;
            }
            set {
                this.tijdstempelTotFieldSpecified = value;
                this.RaisePropertyChanged("tijdstempelTotSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getNieuweStatussenProcesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StatusResultaat[] getNieuweStatussenProcesReturnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public StatusResultaat[] getNieuweStatussenProcesReturn {
            get {
                return this.getNieuweStatussenProcesReturnField;
            }
            set {
                this.getNieuweStatussenProcesReturnField = value;
                this.RaisePropertyChanged("getNieuweStatussenProcesReturn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNieuweStatussenProcesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public BivConnection.CSStatusInformatieService.getNieuweStatussenProcesRequest getNieuweStatussenProcesRequest;
        
        public getNieuweStatussenProcesRequest1() {
        }
        
        public getNieuweStatussenProcesRequest1(BivConnection.CSStatusInformatieService.getNieuweStatussenProcesRequest getNieuweStatussenProcesRequest) {
            this.getNieuweStatussenProcesRequest = getNieuweStatussenProcesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNieuweStatussenProcesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public BivConnection.CSStatusInformatieService.getNieuweStatussenProcesResponse getNieuweStatussenProcesResponse;
        
        public getNieuweStatussenProcesResponse1() {
        }
        
        public getNieuweStatussenProcesResponse1(BivConnection.CSStatusInformatieService.getNieuweStatussenProcesResponse getNieuweStatussenProcesResponse) {
            this.getNieuweStatussenProcesResponse = getNieuweStatussenProcesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getNieuweStatussenRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string berichtsoortField;
        
        private identiteitType identiteitBelanghebbendeField;
        
        private string autorisatieAdresField;
        
        private System.DateTime tijdstempelVanafField;
        
        private bool tijdstempelVanafFieldSpecified;
        
        private System.DateTime tijdstempelTotField;
        
        private bool tijdstempelTotFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string berichtsoort {
            get {
                return this.berichtsoortField;
            }
            set {
                this.berichtsoortField = value;
                this.RaisePropertyChanged("berichtsoort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public identiteitType identiteitBelanghebbende {
            get {
                return this.identiteitBelanghebbendeField;
            }
            set {
                this.identiteitBelanghebbendeField = value;
                this.RaisePropertyChanged("identiteitBelanghebbende");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=2)]
        public string autorisatieAdres {
            get {
                return this.autorisatieAdresField;
            }
            set {
                this.autorisatieAdresField = value;
                this.RaisePropertyChanged("autorisatieAdres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime tijdstempelVanaf {
            get {
                return this.tijdstempelVanafField;
            }
            set {
                this.tijdstempelVanafField = value;
                this.RaisePropertyChanged("tijdstempelVanaf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tijdstempelVanafSpecified {
            get {
                return this.tijdstempelVanafFieldSpecified;
            }
            set {
                this.tijdstempelVanafFieldSpecified = value;
                this.RaisePropertyChanged("tijdstempelVanafSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime tijdstempelTot {
            get {
                return this.tijdstempelTotField;
            }
            set {
                this.tijdstempelTotField = value;
                this.RaisePropertyChanged("tijdstempelTot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tijdstempelTotSpecified {
            get {
                return this.tijdstempelTotFieldSpecified;
            }
            set {
                this.tijdstempelTotFieldSpecified = value;
                this.RaisePropertyChanged("tijdstempelTotSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/")]
    public partial class getNieuweStatussenResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StatusResultaat[] getNieuweStatussenReturnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public StatusResultaat[] getNieuweStatussenReturn {
            get {
                return this.getNieuweStatussenReturnField;
            }
            set {
                this.getNieuweStatussenReturnField = value;
                this.RaisePropertyChanged("getNieuweStatussenReturn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNieuweStatussenRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public BivConnection.CSStatusInformatieService.getNieuweStatussenRequest getNieuweStatussenRequest;
        
        public getNieuweStatussenRequest1() {
        }
        
        public getNieuweStatussenRequest1(BivConnection.CSStatusInformatieService.getNieuweStatussenRequest getNieuweStatussenRequest) {
            this.getNieuweStatussenRequest = getNieuweStatussenRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNieuweStatussenResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logius.nl/digipoort/koppelvlakservices/1.2/", Order=0)]
        public BivConnection.CSStatusInformatieService.getNieuweStatussenResponse getNieuweStatussenResponse;
        
        public getNieuweStatussenResponse1() {
        }
        
        public getNieuweStatussenResponse1(BivConnection.CSStatusInformatieService.getNieuweStatussenResponse getNieuweStatussenResponse) {
            this.getNieuweStatussenResponse = getNieuweStatussenResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StatusinformatieService_V1_2Channel : BivConnection.CSStatusInformatieService.StatusinformatieService_V1_2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StatusinformatieService_V1_2Client : System.ServiceModel.ClientBase<BivConnection.CSStatusInformatieService.StatusinformatieService_V1_2>, BivConnection.CSStatusInformatieService.StatusinformatieService_V1_2 {
        
        public StatusinformatieService_V1_2Client() {
        }
        
        public StatusinformatieService_V1_2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StatusinformatieService_V1_2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatusinformatieService_V1_2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatusinformatieService_V1_2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BivConnection.CSStatusInformatieService.getBerichtsoortenResponse1 BivConnection.CSStatusInformatieService.StatusinformatieService_V1_2.getBerichtsoorten(BivConnection.CSStatusInformatieService.getBerichtsoortenRequest1 request) {
            return base.Channel.getBerichtsoorten(request);
        }
        
        public BivConnection.CSStatusInformatieService.getBerichtsoortenResponse getBerichtsoorten(BivConnection.CSStatusInformatieService.getBerichtsoortenRequest getBerichtsoortenRequest) {
            BivConnection.CSStatusInformatieService.getBerichtsoortenRequest1 inValue = new BivConnection.CSStatusInformatieService.getBerichtsoortenRequest1();
            inValue.getBerichtsoortenRequest = getBerichtsoortenRequest;
            BivConnection.CSStatusInformatieService.getBerichtsoortenResponse1 retVal = ((BivConnection.CSStatusInformatieService.StatusinformatieService_V1_2)(this)).getBerichtsoorten(inValue);
            return retVal.getBerichtsoortenResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BivConnection.CSStatusInformatieService.getBerichtsoortenResponse1> BivConnection.CSStatusInformatieService.StatusinformatieService_V1_2.getBerichtsoortenAsync(BivConnection.CSStatusInformatieService.getBerichtsoortenRequest1 request) {
            return base.Channel.getBerichtsoortenAsync(request);
        }
        
        public System.Threading.Tasks.Task<BivConnection.CSStatusInformatieService.getBerichtsoortenResponse1> getBerichtsoortenAsync(BivConnection.CSStatusInformatieService.getBerichtsoortenRequest getBerichtsoortenRequest) {
            BivConnection.CSStatusInformatieService.getBerichtsoortenRequest1 inValue = new BivConnection.CSStatusInformatieService.getBerichtsoortenRequest1();
            inValue.getBerichtsoortenRequest = getBerichtsoortenRequest;
            return ((BivConnection.CSStatusInformatieService.StatusinformatieService_V1_2)(this)).getBerichtsoortenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BivConnection.CSStatusInformatieService.getProcessenResponse1 BivConnection.CSStatusInformatieService.StatusinformatieService_V1_2.getProcessen(BivConnection.CSStatusInformatieService.getProcessenRequest1 request) {
            return base.Channel.getProcessen(request);
        }
        
        public BivConnection.CSStatusInformatieService.getProcessenResponse getProcessen(BivConnection.CSStatusInformatieService.getProcessenRequest getProcessenRequest) {
            BivConnection.CSStatusInformatieService.getProcessenRequest1 inValue = new BivConnection.CSStatusInformatieService.getProcessenRequest1();
            inValue.getProcessenRequest = getProcessenRequest;
            BivConnection.CSStatusInformatieService.getProcessenResponse1 retVal = ((BivConnection.CSStatusInformatieService.StatusinformatieService_V1_2)(this)).getProcessen(inValue);
            return retVal.getProcessenResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BivConnection.CSStatusInformatieService.getProcessenResponse1> BivConnection.CSStatusInformatieService.StatusinformatieService_V1_2.getProcessenAsync(BivConnection.CSStatusInformatieService.getProcessenRequest1 request) {
            return base.Channel.getProcessenAsync(request);
        }
        
        public System.Threading.Tasks.Task<BivConnection.CSStatusInformatieService.getProcessenResponse1> getProcessenAsync(BivConnection.CSStatusInformatieService.getProcessenRequest getProcessenRequest) {
            BivConnection.CSStatusInformatieService.getProcessenRequest1 inValue = new BivConnection.CSStatusInformatieService.getProcessenRequest1();
            inValue.getProcessenRequest = getProcessenRequest;
            return ((BivConnection.CSStatusInformatieService.StatusinformatieService_V1_2)(this)).getProcessenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BivConnection.CSStatusInformatieService.getStatussenProcesResponse1 BivConnection.CSStatusInformatieService.StatusinformatieService_V1_2.getStatussenProces(BivConnection.CSStatusInformatieService.getStatussenProcesRequest1 request) {
            return base.Channel.getStatussenProces(request);
        }
        
        public BivConnection.CSStatusInformatieService.getStatussenProcesResponse getStatussenProces(BivConnection.CSStatusInformatieService.getStatussenProcesRequest getStatussenProcesRequest) {
            BivConnection.CSStatusInformatieService.getStatussenProcesRequest1 inValue = new BivConnection.CSStatusInformatieService.getStatussenProcesRequest1();
            inValue.getStatussenProcesRequest = getStatussenProcesRequest;
            BivConnection.CSStatusInformatieService.getStatussenProcesResponse1 retVal = ((BivConnection.CSStatusInformatieService.StatusinformatieService_V1_2)(this)).getStatussenProces(inValue);
            return retVal.getStatussenProcesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BivConnection.CSStatusInformatieService.getStatussenProcesResponse1> BivConnection.CSStatusInformatieService.StatusinformatieService_V1_2.getStatussenProcesAsync(BivConnection.CSStatusInformatieService.getStatussenProcesRequest1 request) {
            return base.Channel.getStatussenProcesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BivConnection.CSStatusInformatieService.getStatussenProcesResponse1> getStatussenProcesAsync(BivConnection.CSStatusInformatieService.getStatussenProcesRequest getStatussenProcesRequest) {
            BivConnection.CSStatusInformatieService.getStatussenProcesRequest1 inValue = new BivConnection.CSStatusInformatieService.getStatussenProcesRequest1();
            inValue.getStatussenProcesRequest = getStatussenProcesRequest;
            return ((BivConnection.CSStatusInformatieService.StatusinformatieService_V1_2)(this)).getStatussenProcesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BivConnection.CSStatusInformatieService.getNieuweStatussenProcesResponse1 BivConnection.CSStatusInformatieService.StatusinformatieService_V1_2.getNieuweStatussenProces(BivConnection.CSStatusInformatieService.getNieuweStatussenProcesRequest1 request) {
            return base.Channel.getNieuweStatussenProces(request);
        }
        
        public BivConnection.CSStatusInformatieService.getNieuweStatussenProcesResponse getNieuweStatussenProces(BivConnection.CSStatusInformatieService.getNieuweStatussenProcesRequest getNieuweStatussenProcesRequest) {
            BivConnection.CSStatusInformatieService.getNieuweStatussenProcesRequest1 inValue = new BivConnection.CSStatusInformatieService.getNieuweStatussenProcesRequest1();
            inValue.getNieuweStatussenProcesRequest = getNieuweStatussenProcesRequest;
            BivConnection.CSStatusInformatieService.getNieuweStatussenProcesResponse1 retVal = ((BivConnection.CSStatusInformatieService.StatusinformatieService_V1_2)(this)).getNieuweStatussenProces(inValue);
            return retVal.getNieuweStatussenProcesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BivConnection.CSStatusInformatieService.getNieuweStatussenProcesResponse1> BivConnection.CSStatusInformatieService.StatusinformatieService_V1_2.getNieuweStatussenProcesAsync(BivConnection.CSStatusInformatieService.getNieuweStatussenProcesRequest1 request) {
            return base.Channel.getNieuweStatussenProcesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BivConnection.CSStatusInformatieService.getNieuweStatussenProcesResponse1> getNieuweStatussenProcesAsync(BivConnection.CSStatusInformatieService.getNieuweStatussenProcesRequest getNieuweStatussenProcesRequest) {
            BivConnection.CSStatusInformatieService.getNieuweStatussenProcesRequest1 inValue = new BivConnection.CSStatusInformatieService.getNieuweStatussenProcesRequest1();
            inValue.getNieuweStatussenProcesRequest = getNieuweStatussenProcesRequest;
            return ((BivConnection.CSStatusInformatieService.StatusinformatieService_V1_2)(this)).getNieuweStatussenProcesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BivConnection.CSStatusInformatieService.getNieuweStatussenResponse1 BivConnection.CSStatusInformatieService.StatusinformatieService_V1_2.getNieuweStatussen(BivConnection.CSStatusInformatieService.getNieuweStatussenRequest1 request) {
            return base.Channel.getNieuweStatussen(request);
        }
        
        public BivConnection.CSStatusInformatieService.getNieuweStatussenResponse getNieuweStatussen(BivConnection.CSStatusInformatieService.getNieuweStatussenRequest getNieuweStatussenRequest) {
            BivConnection.CSStatusInformatieService.getNieuweStatussenRequest1 inValue = new BivConnection.CSStatusInformatieService.getNieuweStatussenRequest1();
            inValue.getNieuweStatussenRequest = getNieuweStatussenRequest;
            BivConnection.CSStatusInformatieService.getNieuweStatussenResponse1 retVal = ((BivConnection.CSStatusInformatieService.StatusinformatieService_V1_2)(this)).getNieuweStatussen(inValue);
            return retVal.getNieuweStatussenResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BivConnection.CSStatusInformatieService.getNieuweStatussenResponse1> BivConnection.CSStatusInformatieService.StatusinformatieService_V1_2.getNieuweStatussenAsync(BivConnection.CSStatusInformatieService.getNieuweStatussenRequest1 request) {
            return base.Channel.getNieuweStatussenAsync(request);
        }
        
        public System.Threading.Tasks.Task<BivConnection.CSStatusInformatieService.getNieuweStatussenResponse1> getNieuweStatussenAsync(BivConnection.CSStatusInformatieService.getNieuweStatussenRequest getNieuweStatussenRequest) {
            BivConnection.CSStatusInformatieService.getNieuweStatussenRequest1 inValue = new BivConnection.CSStatusInformatieService.getNieuweStatussenRequest1();
            inValue.getNieuweStatussenRequest = getNieuweStatussenRequest;
            return ((BivConnection.CSStatusInformatieService.StatusinformatieService_V1_2)(this)).getNieuweStatussenAsync(inValue);
        }
    }
}
